//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEDEPX_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd_emp
    {
        public long EMP_CODE { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NICK_NAME { get; set; }
        public string PHOTO_PATH { get; set; }
    }
}
